title:              Bluewolf Update History
email:              sangmosoft@gmail.com
description:        
author:             sangmosoft
baseurl:            ""
url:                "https://steve92son.github.io"

# Social Profiles
# twitter_username:   SBootstrap
# github_username:    StartBootstrap
# facebook_username:  StartBootstrap
# instagram_username:  
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           3
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# theme: jekyll-theme-clean-blog
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

logo: '/img/logo.png'
default_background: '/img/bg-default.jpg'